version: '3.5'

services:

  bancocadastro:
    image: mariadb
    container_name: bancocadastro
    restart: always
    networks:
      app_net:
        ipv4_address: 172.16.238.05  
    environment:
      MYSQL_ROOT_PASSWORD: fiap37scj
      MYSQL_DATABASE: cadastro_usuario

  microcadastro:
    image: guimbm93/mcadastro:1.0.3
    container_name: mcadastro
    tty: true
    stdin_open: true
    restart: always
    ports:
    - 8081:8080
    networks:
      app_net:
        ipv4_address: 172.16.238.10
    depends_on:
      - bancocadastro   

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24