AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'trip-serverless

  Rest API to manage a Trip

  '
Globals:
  Function:
    Timeout: 20
    MemorySize: 512
    Environment:
      Variables:
        TABLE_NAME: TripTable
        ENDPOINT_OVERRIDE: ''
Resources:
  CreateTripRecordFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://gui-23112020/ca8b9af5cea28b627b0251854b5c5938
      Handler: br.com.fiap.handler.CreateTripRecord::handleRequest
      Runtime: java8
      Policies:
      - DynamoDBCrudPolicy:
          TableName: TripTable
      Events:
        CreateStudyRecord:
          Type: Api
          Properties:
            Path: /trips
            Method: post
  GetTripsRecordsByCityFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://gui-23112020/ca8b9af5cea28b627b0251854b5c5938
      Handler: br.com.fiap.handler.GetTripsRecordsByCity::handleRequest
      Runtime: java8
      Policies:
      - DynamoDBCrudPolicy:
          TableName: TripTable
      Events:
        GetStudyRecordsByTag:
          Type: Api
          Properties:
            Path: /trips/{country}
            Method: get
            RequestParameters:
            - method.request.querystring.city
  TripTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: trip
      AttributeDefinitions:
      - AttributeName: country
        AttributeType: S
      - AttributeName: dateTimeCreation
        AttributeType: S
      - AttributeName: city
        AttributeType: S
      - AttributeName: reason
        AttributeType: S
      KeySchema:
      - AttributeName: country
        KeyType: HASH
      - AttributeName: dateTimeCreation
        KeyType: RANGE
      LocalSecondaryIndexes:
      - IndexName: cityIndex
        KeySchema:
        - AttributeName: country
          KeyType: HASH
        - AttributeName: city
          KeyType: RANGE
        Projection:
          ProjectionType: ALL
      - IndexName: reasonIndex
        KeySchema:
        - AttributeName: country
          KeyType: HASH
        - AttributeName: reason
          KeyType: RANGE
        Projection:
          ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST
Outputs:
  CreateStudyRecordFunction:
    Description: CreateTripRecord Lambda Function ARN
    Value: CreateTripRecordFunction.Arn
  GetTripsRecordsByCityFunction:
    Description: GetTripsRecordsByCityFunction Lambda Function ARN
    Value: GetTripsRecordsByCityFunction.Arn
